#include <stddef.h>
#include <wsksymdef.h>

#define KS_KEYCODE(v)	((v) | 0xe000)
#define KC(n)		KS_KEYCODE(n)

// SEL4 modified keydesc for use with keyboard driver
const uint16_t hidkbd_keydesc_us[] = {
/*  pos      command		normal		shifted */
    KC(4), 			    KS_a,           KS_A,
    KC(5), 			    KS_b,           KS_B,
    KC(6), 			    KS_c,           KS_C,
    KC(7), 			    KS_d,           KS_D,
    KC(8), 			    KS_e,           KS_E,
    KC(9), 			    KS_f,           KS_F,
    KC(10), 			KS_g,           KS_G,
    KC(11), 			KS_h,           KS_H,
    KC(12), 			KS_i,           KS_I,
    KC(13), 			KS_j,           KS_J,
    KC(14), 			KS_k,           KS_K,
    KC(15), 			KS_l,           KS_L,
    KC(16), 			KS_m,           KS_M,
    KC(17), 			KS_n,           KS_N,
    KC(18), 			KS_o,           KS_O,
    KC(19), 			KS_p,           KS_P,
    KC(20), 			KS_q,           KS_Q,
    KC(21), 			KS_r,           KS_R,
    KC(22), 			KS_s,           KS_S,
    KC(23), 			KS_t,           KS_T,
    KC(24), 			KS_u,           KS_U,
    KC(25), 			KS_v,           KS_V,
    KC(26), 			KS_w,           KS_W,
    KC(27), 			KS_x,           KS_X,
    KC(28), 			KS_y,           KS_Y,
    KC(29), 			KS_z,           KS_Z,
    KC(30),  			KS_1,		KS_exclam,
    KC(31),  			KS_2,		KS_at,
    KC(32),  			KS_3,		KS_numbersign,
    KC(33),  			KS_4,		KS_dollar,
    KC(34),  			KS_5,		KS_percent,
    KC(35),  			KS_6,		KS_asciicircum,
    KC(36),  			KS_7,		KS_ampersand,
    KC(37),  			KS_8,		KS_asterisk,
    KC(38), 			KS_9,		KS_parenleft,
    KC(39), 			KS_0,		KS_parenright,
    KC(40), 			KS_Return,  KS_Return,
    KC(41),             KS_Cmd_Debugger,	KS_Escape,
    KC(42), 			KS_BackSpace,KS_BackSpace,
    KC(43), 			KS_Tab,     KS_Tab,
    KC(44), 			KS_space,   KS_space,
    KC(45), 			KS_minus,	KS_underscore,
    KC(46), 			KS_equal,	KS_plus,
    KC(47), 			KS_bracketleft,	KS_braceleft,
    KC(48), 			KS_bracketright,KS_braceright,
    KC(49), 			KS_backslash,	KS_bar,
    KC(50), 			KS_backslash,	KS_bar,
    KC(51), 			KS_semicolon,	KS_colon,
    KC(52), 			KS_apostrophe,	KS_quotedbl,
    KC(53), 			KS_grave,	KS_asciitilde,
    KC(54), 			KS_comma,	KS_less,
    KC(55), 			KS_period,	KS_greater,
    KC(56), 			KS_slash,	KS_question,
    KC(57), 			KS_Caps_Lock,
    KC(58),             KS_Cmd_Screen0,	KS_f1,
    KC(59),             KS_Cmd_Screen1,	KS_f2,
    KC(60),             KS_Cmd_Screen2,	KS_f3,
    KC(61),             KS_Cmd_Screen3,	KS_f4,
    KC(62),             KS_Cmd_Screen4,	KS_f5,
    KC(63),             KS_Cmd_Screen5,	KS_f6,
    KC(64),             KS_Cmd_Screen6,	KS_f7,
    KC(65),             KS_Cmd_Screen7,	KS_f8,
    KC(66),             KS_Cmd_Screen8,	KS_f9,
    KC(67),             KS_Cmd_Screen9,	KS_f10,
    KC(68), 			KS_f11,
    KC(69), 			KS_f12,
    KC(70),			    KS_Print_Screen,
    KC(71), 			KS_Hold_Screen,
    KC(72),			KS_Pause,
    KC(73),			KS_Insert,
    KC(74),			KS_Home,
    KC(75), KS_Cmd_ScrollFastUp, KS_Prior,
    KC(76),			KS_Delete,
    KC(77),			KS_End,
    KC(78), KS_Cmd_ScrollFastDown, KS_Next,
    KC(79),			KS_Right,
    KC(80),			KS_Left,
    KC(81),			KS_Down,
    KC(82),			KS_Up,
    KC(83), 			KS_Num_Lock,
    KC(84),			KS_KP_Divide,
    KC(85), 			KS_KP_Multiply,
    KC(86), 			KS_KP_Subtract,
    KC(87), 			KS_KP_Add,
    KC(88),			KS_KP_Enter,
    KC(89), 			KS_KP_End,	KS_KP_1,
    KC(90), 			KS_KP_Down,	KS_KP_2,
    KC(91), KS_Cmd_ScrollFastDown, KS_KP_Next,	KS_KP_3,
    KC(92), 			KS_KP_Left,	KS_KP_4,
    KC(93), 			KS_KP_Begin,	KS_KP_5,
    KC(94), 			KS_KP_Right,	KS_KP_6,
    KC(95), 			KS_KP_Home,	KS_KP_7,
    KC(96), 			KS_KP_Up,	KS_KP_8,
    KC(97), KS_Cmd_ScrollFastUp, KS_KP_Prior,	KS_KP_9,
    KC(98), 			KS_KP_Insert,	KS_KP_0,
    KC(99), 			KS_KP_Delete,	KS_KP_Decimal,
    KC(100),			KS_backslash,	KS_bar,
    KC(101),			KS_Menu,
/* ... */
    KC(104), 			KS_f13,
    KC(105), 			KS_f14,
    KC(106), 			KS_f15,
    KC(107), 			KS_f16,
/* ... */
    KC(109),			KS_Power,
/* ... many unmapped keys ... */
    KC(224),  KS_Cmd1,		KS_Control_L,
    KC(225), 			KS_Shift_L,
    KC(226),  KS_Cmd2,		KS_Alt_L,
    KC(227),			KS_Meta_L,
    KC(228),			KS_Control_R,
    KC(229), 			KS_Shift_R,
    KC(230),			KS_Alt_R,	KS_Multi_key,
    KC(231),			KS_Meta_R,
};
